Docked composer
salesforce/design-system-react pull request #3062
Opened 2022-08-26 17:30 UTC by 2FALockedMeOutOfMyAcct

### Additional description
Adds [Docked Composer](https://www.lightningdesignsystem.com/components/docked-composer/) to DSR
<img width="484" alt="Screen Shot 2022-08-26 at 10 29 48 AM" src="https://user-images.githubusercontent.com/112126271/186960021-f7e9b3d3-b8be-4d24-9a3e-165ceb951da0.png">

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] CircleCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

2022-08-26 18:56 UTC, meizibupt commented on components/docked-composer/index.jsx
> +								title="Minimize"
should we localize titles?

2022-08-26 18:58 UTC, meizibupt commented on components/docked-composer/index.jsx
> +	header: PropTypes.string,
should we allow user to add a node for header too?

2022-08-26 18:59 UTC, meizibupt commented on components/docked-composer/index.jsx
> +	/**
we can also add a css class prop to allow overriding  css

2022-08-26 19:10 UTC, alexxpan commented on components/docked-composer/__examples__/base.jsx
> +		isOpen: true,
This naming convention is a bit confusing, do you think `isExpanded` and `isOpen` would be a bit less ambiguous?

2022-08-29 19:16 UTC, 2FALockedMeOutOfMyAcct commented
Minimized and expanded states:
<img width="489" alt="Screen Shot 2022-08-29 at 12 14 29 PM" src="https://user-images.githubusercontent.com/112126271/187280314-adf08b7c-c6bf-495b-8eb9-782bc1d35957.png">
<img width="484" alt="Screen Shot 2022-08-29 at 12 14 43 PM" src="https://user-images.githubusercontent.com/112126271/187280319-758cb6ce-7cb6-47fd-9881-da59ee8e93d5.png">
3 votes in favor of this behavior: @gfyhui , @alexxpan and Jonathon

2022-08-29 20:45 UTC, meizibupt submitted a review, later dismissed

2022-08-29 21:03 UTC, alexxpan submitted a review, later dismissed

2022-08-29 21:36 UTC, meizibupt approved these changes

2022-08-29 21:42 UTC, garygong submitted a review, later dismissed

2022-08-29 22:13 UTC, alexzherdev commented on components/docked-composer/__tests__/docked-composer.browser-test.jsx
> +// Import your internal dependencies (for example):
These comments seem like they can be removed

2022-08-29 22:27 UTC, interactivellama requested changes
First, this is a great pull request! I did not pull this down to manually test it, but did left a few minor request and referenced the overview doc. Thank you for this great contribution!

2022-08-29 22:27 UTC, interactivellama commented on components/docked-composer/__examples__/minimized.jsx
> +					onMinimize: this.handleMinimize,
I haven't dove deep into this yet, but these look like on request pre-state change actions.
https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#prefix-onrequestaction-to-pre-state-change-callbacks-functions

2022-08-29 22:27 UTC, interactivellama commented on components/docked-composer/index.jsx
> +					aria-labelledby="dialog-heading-id-1"
All ids need to be prefixed by an id or a random id if not set `this.generatedId`

2022-08-29 22:27 UTC, interactivellama commented on components/docked-composer/index.jsx
> +									title={this.props.assistiveText?.minimizeButton || 'Minimize'}
I think was would be typically done by a default props object, so no one has to search render functions for text literals.

2022-08-29 22:27 UTC, interactivellama commented on components/docked-composer/index.jsx
> +											this.props.assistiveText?.minimizeButton || 'Minimize',
Same here.

2022-08-29 22:27 UTC, interactivellama commented on components/docked-composer/index.jsx
> +									title={this.props.assistiveText?.expandButton || 'Expand'}
Same.

2022-08-29 22:27 UTC, interactivellama commented on components/docked-composer/index.jsx
> +										icon: this.props.assistiveText?.expandButton || 'Expand',
Same.

2022-08-30 22:44 UTC, interactivellama approved these changes

2022-08-30 23:05 UTC, interactivellama commented
@alexzherdev Merge when you ready to.

2022-08-30 23:22 UTC, alexzherdev commented
Not super important for this simple component, but I wonder if we should encourage new components to be written as functions. At this point I don't think there are any pre-16.8 consumers?

2022-08-30 23:24 UTC, merged

2022-08-31 16:29 UTC, interactivellama commented
@alexzherdev I'm cool with that. Please update the docs when convenient. I believe DataTable has hooks in it.

2022-08-31 16:30 UTC, interactivellama commented
Also, love the account name: @2FALockedMeOutOfMyAcct

2022-08-31 21:14 UTC, 2FALockedMeOutOfMyAcct commented
Thanks for the reviews and merging. When will the next DSR release be @interactivellama @alexzherdev ?

2022-09-01 22:16 UTC, alexzherdev commented
@interactivellama is the automated release build still broken?

2022-09-01 22:23 UTC, interactivellama commented
Yes.

I could use some help in triaging the authentication, since the security protections went up.

2022-09-07 16:28 UTC, interactivellama commented
@2FALockedMeOutOfMyAcct Please open a release PR and I will pull down and push up a tag.

2022-09-08 19:10 UTC, alexzherdev commented
@interactivellama I opened #3063 if that's what you meant?

2022-09-08 19:57 UTC, interactivellama commented
I'll try to get this out by End of week.

2022-09-09 21:11 UTC, interactivellama commented
https://github.com/salesforce/design-system-react/releases/tag/v0.10.49

2022-09-09 23:11 UTC, interactivellama commented
There are additional issues with the NPM publishing process. I'm in talks with Jim in OSS group on getting different permissions set up. The tag is present in Github but we do not have a NPM package up today.